services:
  redis:
    image: redis:latest
    container_name: tn_sb_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/redis/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
  chromadb:
    image: chromadb/chroma:latest
    container_name: tn_sb_chroma
    volumes:
      - chroma_data:/chroma/data
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/data # this is the default path, change it as needed
    ports:
      - 8000:8000
    restart: unless-stopped
volumes:
  redis_data:
  chroma_data:
